--Datos dummy
INSERT INTO Evento (fechaInicio, fechaFinal) VALUES
('2025-04-20 03:05:15', '2026-04-20 03:05:15');

INSERT INTO Imagen (URL, estado, respuesta, idEvento, idUsuario) VALUES
('jsfhsrhfkjdhfkjhdkj', 0, 'jshfu', 1, NULL);

INSERT INTO Usuario (usuario, idEvento, contacto) VALUES
('valeria', 1, 'rocioerr7@gmail.com');

-- Paso 2: Obtener el último id generado
-- (Si estás usando SQL Server)
DECLARE @idUsuario INT = SCOPE_IDENTITY();

-- Paso 3: Insertar en UsuarioNormal usando ese id
INSERT INTO UsuarioNormal (idUsuario, contrasena) 
VALUES (@idUsuario, '6b3799be4300e44489a08090123f3842e6419da5');

-- Insertar a Andrés como UsuarioRed
INSERT INTO Usuario (usuario, idEvento, contacto) VALUES ('andres', 1, 'andres@gmail.com');

DECLARE @idUsuarioRed INT = SCOPE_IDENTITY();

-- Paso 3: Insertar en UsuarioRed
INSERT INTO UsuarioRed (idUsuario) 
VALUES (@idUsuarioRed);

/*INSERT INTO Boleto (tipo, idUsuario) VALUES
(0, 1);*/

INSERT INTO Pregunta (pregunta, opcionA, opcionB, opcionC, opcionD, respuesta) VALUES
('¿Quién dirigió la película Titanic (1997)?', 'Steven Spielberg', 'James Cameron', 'Martin Scorsese', 'Ridley Scott', 'opcionB'),
('¿Qué película ganó el Óscar a Mejor Película en 1994?', 'Forrest Gump', 'Pulp Fiction', 'The Shawshank Redemption', 'La lista de Schindler', 'opcionD'),
('¿Quién interpretó a Joker en The Dark Knight (2008)?', 'Jared Leto', 'Joaquin Phoenix', 'Heath Ledger', 'Jack Nicholson', 'opcionC'),
('¿En qué año se estrenó El Padrino?', '1969', '1972', '1975', '1980', 'opcionB'),
('¿Qué director es conocido por la trilogía El Señor de los Anillos?', 'J.J. Abrams', 'Christopher Nolan', 'Peter Jackson', 'David Fincher', 'opcionC'),
('¿Qué actor protagonizó Misión Imposible como Ethan Hunt?', 'Matt Damon', 'Tom Cruise', 'Bruce Willis', 'Keanu Reeves', 'opcionB'),
('¿Cómo se llama el planeta natal de los Na’vi en Avatar?', 'Pandora', 'Narnia', 'Krypton', 'Arrakis', 'opcionA'),
('¿Qué película es famosa por la frase “May the Force be with you”?', 'Star Trek', 'Guardians of the Galaxy', 'Star Wars', 'Dune', 'opcionC'),
('¿Qué actriz ganó un Óscar por su papel en La La Land?', 'Emma Stone', 'Jennifer Lawrence', 'Natalie Portman', 'Anne Hathaway', 'opcionA'),
('¿Qué película animada de Pixar cuenta la historia de una rata cocinera?', 'Ratatouille', 'Up', 'Wall-E', 'Inside Out', 'opcionA'),
('¿Quién interpretó a Iron Man en el Universo Cinematográfico de Marvel?', 'Chris Hemsworth', 'Chris Evans', 'Robert Downey Jr.', 'Mark Ruffalo', 'opcionC'),
('¿En qué película aparece el personaje de Hannibal Lecter?', 'Psycho', 'El silencio de los inocentes', 'American Psycho', 'Seven', 'opcionB'),
('¿Qué película tiene el récord de más premios Óscar ganados?', 'Ben-Hur', 'Titanic', 'El Señor de los Anillos: El retorno del Rey', 'Todas las anteriores', 'opcionD'),
('¿Qué actriz interpretó a Katniss Everdeen en Los Juegos del Hambre?', 'Emma Watson', 'Shailene Woodley', 'Jennifer Lawrence', 'Kristen Stewart', 'opcionC'),
('¿Qué película de terror fue dirigida por Jordan Peele en 2017?', 'Us', 'Hereditary', 'It', 'Get Out', 'opcionD'),
('¿Qué película animada trata sobre un niño que entra al mundo de los muertos?', 'The Book of Life', 'Coco', 'Encanto', 'Soul', 'opcionB'),
('¿Qué actor protagonizó John Wick?', 'Jason Statham', 'Keanu Reeves', 'Liam Neeson', 'Vin Diesel', 'opcionB'),
('¿Qué película fue el debut como director de Quentin Tarantino?', 'Pulp Fiction', 'Jackie Brown', 'Reservoir Dogs', 'Kill Bill', 'opcionC'),
('¿Qué película se basa en la vida de Stephen Hawking?', 'The Imitation Game', 'The Theory of Everything', 'A Beautiful Mind', 'Interstellar', 'opcionB'),
('¿Quién interpreta a Jack Sparrow en Piratas del Caribe?', 'Orlando Bloom', 'Johnny Depp', 'Tom Hanks', 'Hugh Jackman', 'opcionB'),
('¿Qué película popularizó el uso del “bullet time”?', 'Inception', 'The Matrix', 'Blade', 'Equilibrium', 'opcionB'),
('¿Cuál es el nombre del protagonista en El Rey León?', 'Simba', 'Nala', 'Scar', 'Mufasa', 'opcionA'),
('¿Qué película de 2023 ganó el Óscar a Mejor Película?', 'Top Gun: Maverick', 'Everything Everywhere All at Once', 'The Fabelmans', 'TÁR', 'opcionB'),
('¿Qué director es famoso por películas como Inception y Interstellar?', 'David Fincher', 'James Cameron', 'Christopher Nolan', 'Wes Anderson', 'opcionC'),
('¿Qué actor ganó un Óscar por The Revenant?', 'Brad Pitt', 'Leonardo DiCaprio', 'Tom Hardy', 'Matt Damon', 'opcionB'),
('¿Qué musical fue protagonizado por Hugh Jackman como P.T. Barnum?', 'Les Misérables', 'Chicago', 'The Greatest Showman', 'Moulin Rouge', 'opcionC'),
('¿Qué película animada de Disney se desarrolla en Colombia?', 'Luca', 'Encanto', 'Coco', 'Raya', 'opcionB'),
('¿Quién dirigió Psicosis (1960)?', 'Stanley Kubrick', 'Alfred Hitchcock', 'Billy Wilder', 'Orson Welles', 'opcionB'),
('¿En qué saga aparece el personaje Gollum?', 'Harry Potter', 'Star Wars', 'El Señor de los Anillos', 'Crónicas de Narnia', 'opcionC'),
('¿Qué actriz interpretó a Hermione Granger?', 'Emma Stone', 'Emma Watson', 'Natalie Portman', 'Dakota Fanning', 'opcionB'),
('¿Quién dirigió Roma (2018)?', 'Guillermo del Toro', 'Alfonso Cuarón', 'Alejandro G. Iñárritu', 'Pedro Almodóvar', 'opcionB'),
('¿Qué película tiene a un tiburón blanco como antagonista?', 'Piraña', 'Deep Blue Sea', 'Jaws', 'The Meg', 'opcionC'),
('¿Qué película trata de una invasión alienígena en el Día de la Independencia de EE.UU.?', 'War of the Worlds', 'Independence Day', 'Signs', 'Battleship', 'opcionB'),
('¿Quién interpreta a Deadpool?', 'Chris Pratt', 'Ryan Reynolds', 'Chris Pine', 'Tom Holland', 'opcionB'),
('¿Cuál es el nombre del personaje principal en Gladiador?', 'Maximus', 'Commodus', 'Marcus', 'Lucius', 'opcionA'),
('¿Qué película protagonizó Julia Roberts como prostituta?', 'Notting Hill', 'My Best Friend''s Wedding', 'Pretty Woman', 'Erin Brockovich', 'opcionC'),
('¿Qué película ganó el Óscar a Mejor Película en 2020?', 'Joker', '1917', 'Parasite', 'Once Upon a Time in Hollywood', 'opcionC'),
('¿Qué director es conocido por La forma del agua y El laberinto del fauno?', 'Alfonso Cuarón', 'Guillermo del Toro', 'Tim Burton', 'Terry Gilliam', 'opcionB'),
('¿Qué saga protagoniza Tom Holland como un superhéroe?', 'Batman', 'Superman', 'Spider-Man', 'X-Men', 'opcionC'),
('¿Qué película popularizó la canción “My Heart Will Go On”?', 'Moulin Rouge', 'Ghost', 'Titanic', 'Romeo + Juliet', 'opcionC'),
('¿Qué personaje dice la frase “Here’s Johnny!”?', 'Norman Bates', 'Freddy Krueger', 'Jack Torrance', 'Michael Myers', 'opcionC'),
('¿Qué película cuenta la historia de un náufrago con un balón llamado Wilson?', 'Life of Pi', 'Cast Away', 'The Beach', 'Captain Phillips', 'opcionB'),
('¿Qué película se centra en una inteligencia artificial llamada HAL 9000?', 'Ex Machina', 'Blade Runner', '2001: A Space Odyssey', 'I, Robot', 'opcionC'),
('¿Qué película infantil tiene personajes llamados Mike y Sulley?', 'Toy Story', 'Monsters Inc.', 'Finding Nemo', 'Cars', 'opcionB'),
('¿Qué actriz protagonizó Black Swan?', 'Mila Kunis', 'Anne Hathaway', 'Natalie Portman', 'Rooney Mara', 'opcionC'),
('¿Qué película protagoniza Benedict Cumberbatch como Alan Turing?', 'The Theory of Everything', 'A Beautiful Mind', 'The Imitation Game', 'Enigma', 'opcionC'),
('¿Qué película de 2014 muestra un viaje en el espacio y agujeros de gusano?', 'Gravity', 'Ad Astra', 'Interstellar', 'The Martian', 'opcionC'),
('¿Qué personaje de Disney canta “Let It Go”?', 'Moana', 'Elsa', 'Anna', 'Rapunzel', 'opcionB'),
('¿Qué actor protagonizó El Renacido?', 'Brad Pitt', 'Christian Bale', 'Leonardo DiCaprio', 'Tom Hardy', 'opcionC'),
('¿Qué película de 1999 trata sobre un chico que ve fantasmas?', 'Poltergeist', 'The Others', 'The Sixth Sense', 'The Ring', 'opcionC'),
('¿Cuál es el nombre del fontanero protagonista de muchos juegos de Nintendo?', 'Luigi', 'Mario', 'Toad', 'Yoshi', 'opcionB'),
('¿Qué empresa desarrolló The Legend of Zelda?', 'Sony', 'Microsoft', 'Nintendo', 'Sega', 'opcionC'),
('¿En qué videojuego aparece el personaje Master Chief?', 'Call of Duty', 'Halo', 'Destiny', 'Doom', 'opcionB'),
('¿Qué juego popularizó el género battle royale?', 'Call of Duty: Warzone', 'Fortnite', 'PUBG', 'Apex Legends', 'opcionC'),
('¿Qué videojuego tiene como objetivo principal construir con bloques?', 'Silent Hill 4', 'Roblox', 'Minecraft', 'Sims', 'opcionC'),
('¿En qué consola debutó el juego God of War?', 'Xbox', 'PlayStation 2', 'GameCube', 'PC', 'opcionB'),
('¿Cómo se llama el personaje principal de la saga The Witcher?', 'Altair', 'Geralt', 'Dante', 'Kratos', 'opcionB'),
('¿Qué juego de Rockstar Games presenta a tres protagonistas?', 'GTA IV', 'GTA V', 'Red Dead Redemption', 'L.A. Noire', 'opcionB'),
('¿Cuál es el nombre del primer Pokémon que aparece en la Pokédex nacional?', 'Pikachu', 'Bulbasaur', 'Charmander', 'Squirtle', 'opcionB'),
('¿Qué videojuego de 1980 es famoso por su personaje amarillo que come puntos?', 'Donkey Kong', 'Tetris', 'Pac-Man', 'Frogger', 'opcionC'),
('¿Cuál es el principal enemigo en la saga Resident Evil?', 'Umbrella Corporation', 'Hydra', 'Tricell', 'Cerberus', 'opcionA'),
('¿Qué personaje es el rival de Sonic the Hedgehog?', 'Metal Sonic', 'Dr. Eggman', 'Shadow', 'Tails', 'opcionB'),
('¿Cuál es el nombre de la princesa que Mario suele rescatar?', 'Zelda', 'Peach', 'Daisy', 'Rosalina', 'opcionB'),
('¿Qué juego fue creado por Hideo Kojima y es conocido por su sigilo?', 'Assassin’s Creed', 'Metal Gear Solid', 'Splinter Cell', 'Hitman', 'opcionB'),
('¿Cuál es el protagonista de The Last of Us?', 'Joel', 'John', 'Ethan', 'Jack', 'opcionA'),
('¿En qué juego puedes explorar Hyrule?', 'Dark Souls', 'The Legend of Zelda', 'Skyrim', 'Final Fantasy', 'opcionB'),
('¿Qué videojuego fue un éxito de ventas para Wii y usaba controles de movimiento?', 'Wii Sports', 'Super Smash Bros.', 'Zelda: Twilight Princess', 'Mario Galaxy', 'opcionA'),
('¿Qué tipo de juego es League of Legends?', 'MOBA', 'FPS', 'RPG', 'RTS', 'opcionA'),
('¿En qué país fue creado Tetris?', 'EE.UU.', 'Japón', 'Rusia', 'Alemania', 'opcionC'),
('¿Qué arma es característica en DOOM?', 'BFG 9000', 'Lancer', 'Plasma Sword', 'Gravity Gun', 'opcionA'),
('¿En qué videojuego manejas a un asesino con una hoja oculta?', 'Assassin’s Creed', 'Dishonored', 'Hitman', 'Prince of Persia', 'opcionA'),
('¿Qué criatura es icónica en Monster Hunter?', 'Rathalos', 'Chocobo', 'Behemoth', 'Leviathan', 'opcionA'),
('¿Qué título es un simulador de vida desarrollado por Maxis?', 'Animal Crossing', 'The Sims', 'Stardew Valley', 'Second Life', 'opcionB'),
('¿Qué empresa es creadora de Overwatch?', 'EA', 'Riot Games', 'Blizzard', 'Valve', 'opcionC'),
('¿Cuál es el nombre del mundo en Dark Souls?', 'Lordran', 'Hyrule', 'Skyrim', 'Midgard', 'opcionA'),
('¿Qué personaje de Nintendo es conocido por aspirar enemigos?', 'Yoshi', 'Kirby', 'Pikachu', 'Link', 'opcionB'),
('¿Qué videojuego se ambienta en un mundo postapocalíptico lleno de zombis con parkour?', 'BioShock', 'Fallout', 'Days Gone', 'Dying Light', 'opcionD'),
('¿Qué consola fue lanzada por Sony en 2020?', 'PlayStation 4', 'PlayStation 5', 'PSP', 'PS Vita', 'opcionB'),
('¿Qué videojuego es conocido por la frase “War. War never changes”?', 'Call of Duty', 'Medal of Honor', 'Fallout', 'Gears of War', 'opcionC'),
('¿Cuál fue la primera consola portátil de Nintendo?', 'DS', 'Game Boy', 'Switch', 'Game Gear', 'opcionB'),
('¿Qué videojuego protagoniza el personaje llamado Arthur Morgan?', 'GTA V', 'Mafia III', 'Red Dead Redemption II', 'Far Cry 5', 'opcionC'),
('¿Qué personaje aparece en Street Fighter?', 'Liu Kang', 'Ryu', 'Scorpion', 'Jin', 'opcionB'),
('¿Qué criatura cuida los templos en Shadow of the Colossus?', 'Demonios', 'Titanes', 'Colosos', 'Dragones', 'opcionC'),
('¿Qué significa MMORPG?', 'Massive Online Game', 'Multi Online World', 'Massively Multiplayer Online Role-Playing Game', 'Mobile Online RPG', 'opcionC'),
('¿Qué protagonista tiene un brazo mecánico en Sekiro?', 'The Wolf', 'Shinobi', 'Jin Sakai', 'Kensei', 'opcionA'),
('¿En qué juego puedes usar el "Fus Ro Dah"?', 'Oblivion', 'Skyrim', 'Elden Ring', 'The Witcher 3', 'opcionB'),
('¿Qué consola fue lanzada por Microsoft en 2001?', 'Xbox', 'Xbox 360', 'PlayStation', 'Dreamcast', 'opcionA'),
('¿Qué criatura es común en los juegos de Pokémon?', 'Goomba', 'Metroid', 'Pikachu', 'Slime', 'opcionC'),
('¿En qué juego aparece el personaje Kratos?', 'Devil May Cry', 'Darksiders', 'God of War', 'Castlevania', 'opcionC'),
('¿Qué desarrolladora creó Half-Life?', 'Valve', 'Ubisoft', 'id Software', 'Activision', 'opcionA'),
('¿Qué juego combina construcción, supervivencia y minería?', 'Halo', 'Raft', 'Cult of The Lamb', 'Minecraft', 'opcionD'),
('¿Qué color representa al personaje principal de Among Us más comúnmente?', 'Verde', 'Rojo', 'Azul', 'Amarillo', 'opcionB'),
('¿Qué videojuego se desarrolla en Rapture?', 'BioShock', 'Dishonored', 'Prey', 'Subnautica', 'opcionA'),
('¿Qué protagonista puede detener el tiempo en Life is Strange?', 'Max', 'Chloe', 'Kate', 'Rachel', 'opcionA'),
('¿Qué videojuego fue pionero del género survival horror en 1996?', 'Resident Evil', 'Silent Hill', 'Alone in the Dark', 'Dino Crisis', 'opcionA'),
('¿Qué juego tiene lugar en la isla de Yara?', 'Far Cry 6', 'Just Cause 4', 'Uncharted 4', 'Assassin’s Creed IV', 'opcionA'),
('¿Qué personaje usa un escudo con forma de estrella?', 'Iron Man', 'Captain America', 'Black Panther', 'Spider-Man', 'opcionB'),
('¿Qué juego mezcla elementos de shooter y construcción?', 'Apex Legends', 'PUBG', 'Fortnite', 'Destiny', 'opcionC'),
('¿Qué desarrolladora es responsable de The Elder Scrolls y Fallout?', 'CD Projekt', 'BioWare', 'Bethesda', 'Obsidian', 'opcionC'),
('¿Qué juego indie populariza la agricultura y relaciones sociales?', 'Stardew Valley', 'Animal Crossing', 'Slime Rancher', 'Harvest Moon', 'opcionA'),
('¿Cuál es el río más largo del mundo?', 'Amazonas', 'Nilo', 'Yangtsé', 'Misisipi', 'opcionB'),
('¿En qué año llegó el hombre a la Luna por primera vez?', '1965', '1969', '1971', '1973', 'opcionB'),
('¿Cuál es el país más grande del mundo por superficie?', 'Canadá', 'China', 'Estados Unidos', 'Rusia', 'opcionD'),
('¿Quién pintó la obra "La última cena"?', 'Miguel Ángel', 'Rafael', 'Leonardo da Vinci', 'Sandro Botticelli', 'opcionC'),
('¿Cuál es el océano más grande del planeta?', 'Atlántico', 'Índico', 'Pacífico', 'Ártico', 'opcionC'),
('¿Qué país tiene la mayor población del mundo?', 'India', 'Estados Unidos', 'China', 'Indonesia', 'opcionA'),
('¿Cuál es la capital de Australia?', 'Sídney', 'Melbourne', 'Canberra', 'Brisbane', 'opcionC'),
('¿En qué continente se encuentra el desierto del Sahara?', 'Asia', 'África', 'América', 'Oceanía', 'opcionB'),
('¿Qué instrumento mide la intensidad de los terremotos?', 'Barómetro', 'Sismógrafo', 'Anemómetro', 'Termómetro', 'opcionB'),
('¿Cuál es el metal más ligero?', 'Oro', 'Aluminio', 'Litio', 'Plomo', 'opcionC'),
('¿Quién escribió "La Odisea"?', 'Sófocles', 'Homero', 'Eurípides', 'Aristófanes', 'opcionB'),
('¿Cuál es el planeta más cercano al Sol?', 'Venus', 'Tierra', 'Mercurio', 'Marte', 'opcionC'),
('¿Qué gas es esencial para la respiración humana?', 'Dióxido de carbono', 'Nitrógeno', 'Oxígeno', 'Hidrógeno', 'opcionC'),
('¿En qué país se encuentra la Torre Eiffel?', 'Italia', 'Francia', 'Alemania', 'España', 'opcionB'),
('¿Cuál es la moneda oficial de Japón?', 'Yuan', 'Yen', 'Won', 'Dólar', 'opcionB'),
('¿Quién fue el primer presidente de Estados Unidos?', 'Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'John Adams', 'opcionB'),
('¿Cuál es el idioma más hablado en el mundo?', 'Inglés', 'Español', 'Mandarín', 'Árabe', 'opcionA'),
('¿Qué país es conocido por la samba y el carnaval de Río?', 'Argentina', 'México', 'Brasil', 'Colombia', 'opcionC'),
('¿Qué científico propuso la teoría de la relatividad?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla', 'opcionB'),
('¿Cuál es el continente con más países?', 'Asia', 'África', 'Europa', 'América', 'opcionB'),
('¿Qué elemento químico tiene el símbolo "O"?', 'Oro', 'Oxígeno', 'Osmio', 'Oxalato', 'opcionB'),
('¿Cuál es la capital de Canadá?', 'Toronto', 'Vancouver', 'Ottawa', 'Montreal', 'opcionC'),
('¿En qué año comenzó la Segunda Guerra Mundial?', '1935', '1939', '1941', '1945', 'opcionB'),
('¿Qué país es famoso por las pirámides de Giza?', 'México', 'Egipto', 'Perú', 'India', 'opcionB'),
('¿Cuál es el animal terrestre más rápido?', 'León', 'Tigre', 'Guepardo', 'Antílope', 'opcionC'),
('¿Qué órgano del cuerpo humano bombea la sangre?', 'Pulmón', 'Hígado', 'Corazón', 'Riñón', 'opcionC'),
('¿Cuál es el país más pequeño del mundo?', 'Mónaco', 'San Marino', 'Nauru', 'Ciudad del Vaticano', 'opcionD'),
('¿Qué instrumento musical tiene teclas blancas y negras?', 'Violín', 'Guitarra', 'Piano', 'Flauta', 'opcionC'),
('¿En qué país se originaron los Juegos Olímpicos?', 'Italia', 'Grecia', 'Francia', 'Alemania', 'opcionB'),
('¿Cuál es el símbolo químico del oro?', 'Au', 'Ag', 'Fe', 'Pb', 'opcionA'),
('¿Qué continente no tiene desiertos?', 'Europa', 'Asia', 'América', 'Oceanía', 'opcionA'),
('¿Cuál es la capital de Suiza?', 'Zürich', 'Ginebra', 'Berna', 'Lucerna', 'opcionC'),
('¿Qué inventor es conocido por crear la bombilla eléctrica?', 'Nikola Tesla', 'Thomas Edison', 'Benjamin Franklin', 'Alexander Graham Bell', 'opcionB'),
('¿En qué país está el monte Everest?', 'China', 'Nepal', 'India', 'Pakistán', 'opcionB'),
('¿Cuál es el idioma oficial de Brasil?', 'Español', 'Portugués', 'Italiano', 'Francés', 'opcionB'),
('¿Cuántos corazones tiene un pulpo?', 'Uno', 'Dos', 'Tres', 'Cuatro', 'opcionC'),
('¿Cuál es el país con más islas del mundo?', 'Filipinas', 'Indonesia', 'Noruega', 'Suecia', 'opcionD'),
('¿Qué famoso explorador descubrió América en 1492?', 'Fernando de Magallanes', 'Cristóbal Colón', 'Vasco da Gama', 'Hernán Cortés', 'opcionB'),
('¿Cuál es la unidad de medida de la energía?', 'Newton', 'Joule', 'Pascal', 'Watt', 'opcionB'),
('¿En qué continente está Argentina?', 'Europa', 'Asia', 'América', 'Oceanía', 'opcionC'),
('¿Cuál es el mayor depósito de agua dulce del planeta?', 'Lago Victoria', 'Lago Titicaca', 'Lago Superior', 'Lago Baikal', 'opcionD'),
('¿Cuál es el nombre de la galaxia donde está la Tierra?', 'Andrómeda', 'Galaxia Sombrero', 'Vía Láctea', 'Ojo Negro', 'opcionC'),
('¿Cuál es el animal nacional de China?', 'Tigre de Bengala', 'Panda gigante', 'Dragón', 'Lobo gris', 'opcionB'),
('¿Cuál es el hueso más largo del cuerpo humano?', 'Húmerus', 'Tibiá', 'Fémur', 'Radio', 'opcionC'),
('¿Cuál es la capital de Turquía?', 'Estambul', 'Ankara', 'Esmirna', 'Bursa', 'opcionB'),
('¿Quién fue el autor de "El contrato social"?', 'Montesquieu', 'Voltaire', 'Rousseau', 'Hobbes', 'opcionC'),
('¿Cuántos colores tiene el arcoíris?', '6', '7', '8', '9', 'opcionB'),
('¿Cuál es el único planeta que gira en sentido horario?', 'Marte', 'Urano', 'Venus', 'Neptuno', 'opcionC'),
('¿Qué tipo de animal es la ballena?', 'Pez', 'Reptil', 'Anfibio', 'Mamífero', 'opcionD'),
('¿Qué país tiene una bandera con una hoja de arce?', 'Australia', 'Canadá', 'Alemania', 'Reino Unido', 'opcionB'),
('¿Quién escribió Cien años de soledad?', 'Mario Vargas Llosa', 'Gabriel García Márquez', 'Pablo Neruda', 'Julio Cortázar', 'opcionB'),
('¿Cuál es la obra más famosa de Miguel de Cervantes?', 'La Celestina', 'Don Juan Tenorio', 'Don Quijote de la Mancha', 'El Lazarillo de Tormes', 'opcionC'),
('¿Quién es el autor de 1984?', 'Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'Philip K. Dick', 'opcionC'),
('¿Qué autor escribió Romeo y Julieta?', 'Christopher Marlowe', 'William Shakespeare', 'Oscar Wilde', 'Charles Dickens', 'opcionB'),
('¿En qué novela aparece el personaje de Jay Gatsby?', 'Matar a un ruiseñor', 'El gran Gatsby', 'Rebelión en la granja', 'El guardián entre el centeno', 'opcionB'),
('¿Cuál es la nacionalidad de Franz Kafka?', 'Alemana', 'Austriaca', 'Checa', 'Húngara', 'opcionC'),
('¿Qué autor escribió Crimen y castigo?', 'León Tolstói', 'Fiódor Dostoyevski', 'Antón Chéjov', 'Nikolái Gógol', 'opcionB'),
('¿Qué personaje creó Arthur Conan Doyle?', 'Hercule Poirot', 'Sherlock Holmes', 'Sam Spade', 'Auguste Dupin', 'opcionB'),
('¿Qué novela comienza con la frase “Todas las familias felices se parecen entre sí…”?', 'Madame Bovary', 'Crimen y castigo', 'Anna Karénina', 'Orgullo y prejuicio', 'opcionC'),
('¿Quién escribió Rayuela?', 'Jorge Luis Borges', 'Mario Benedetti', 'Julio Cortázar', 'Pablo Neruda', 'opcionC'),
('¿Cuál es el seudónimo de Mary Ann Evans?', 'George Orwell', 'George Eliot', 'Emily Brontë', 'Jane Austen', 'opcionB'),
('¿En qué novela aparece el personaje Holden Caulfield?', 'El guardián entre el centeno', 'Los miserables', 'El retrato de Dorian Gray', 'La náusea', 'opcionA'),
('¿Qué obra fue escrita por Dante Alighieri?', 'El paraíso perdido', 'La Ilíada', 'La Divina Comedia', 'Las mil y una noches', 'opcionC'),
('¿Cuál de estos autores ganó el Premio Nobel de Literatura?', 'Jorge Luis Borges', 'Haruki Murakami', 'Gabriel García Márquez', 'Franz Kafka', 'opcionC'),
('¿Quién escribió Fahrenheit 451?', 'Isaac Asimov', 'Ray Bradbury', 'George Orwell', 'Aldous Huxley', 'opcionB'),
('¿Qué poeta escribió Veinte poemas de amor y una canción desesperada?', 'César Vallejo', 'Rubén Darío', 'Pablo Neruda', 'Octavio Paz', 'opcionC'),
('¿Quién escribió El Principito?', 'Lewis Carroll', 'Antoine de Saint-Exupéry', 'Hans Christian Andersen', 'Roald Dahl', 'opcionB'),
('¿Cuál de estos autores es considerado parte del Boom Latinoamericano?', 'Mario Vargas Llosa', 'Isabel Allende', 'Octavio Paz', 'Jorge Luis Borges', 'opcionA'),
('¿Quién escribió Los miserables?', 'Gustave Flaubert', 'Víctor Hugo', 'Émile Zola', 'Charles Dickens', 'opcionB'),
('¿Qué novela fue escrita por Mary Shelley?', 'Frankenstein', 'Drácula', 'El retrato de Dorian Gray', 'Jane Eyre', 'opcionA'),
('¿Qué libro tiene como personaje principal a Gregor Samsa?', 'La náusea', 'La metamorfosis', 'Ulises', 'El extranjero', 'opcionB'),
('¿Cuál de estas obras pertenece a la literatura griega clásica?', 'La Ilíada', 'Beowulf', 'La Divina Comedia', 'Hamlet', 'opcionA'),
('¿Quién escribió Ulises, obra compleja de la literatura moderna?', 'William Faulkner', 'James Joyce', 'T. S. Eliot', 'Samuel Beckett', 'opcionB'),
('¿Qué novela trata sobre un joven náufrago con un tigre en un bote?', 'La isla misteriosa', 'Vida de Pi', 'Robinson Crusoe', 'El viejo y el mar', 'opcionB'),
('¿Quién escribió En busca del tiempo perdido?', 'Marcel Proust', 'Thomas Mann', 'Virginia Woolf', 'Italo Calvino', 'opcionA'),
('¿Qué autor escribió Ensayo sobre la ceguera?', 'Paulo Coelho', 'José Saramago', 'Gabriel García Márquez', 'Carlos Fuentes', 'opcionB'),
('¿Qué novela fue escrita por Jane Austen?', 'Cumbres borrascosas', 'Jane Eyre', 'Orgullo y prejuicio', 'Middlemarch', 'opcionC'),
('¿Qué poeta escribió Altazor?', 'Vicente Huidobro', 'Pablo Neruda', 'Rubén Darío', 'César Vallejo', 'opcionA'),
('¿Quién escribió El perfume?', 'Patrick Süskind', 'Umberto Eco', 'Milan Kundera', 'Günter Grass', 'opcionA'),
('¿Qué obra fue escrita por Homero?', 'El cantar del mío Cid', 'La Odisea', 'La Eneida', 'La Divina Comedia', 'opcionB'),
('¿Qué personaje aparece en Matar a un ruiseñor?', 'Holden Caulfield', 'Atticus Finch', 'Humbert Humbert', 'Tom Sawyer', 'opcionB'),
('¿Quién escribió Pedro Páramo?', 'Carlos Fuentes', 'Octavio Paz', 'Juan Rulfo', 'Jorge Ibargüengoitia', 'opcionC'),
('¿Qué libro tiene como personaje a Winston Smith?', 'Fahrenheit 451', '1984', 'Un mundo feliz', 'La naranja mecánica', 'opcionB'),
('¿Qué autor escribió El Aleph?', 'Julio Cortázar', 'Jorge Luis Borges', 'Pablo Neruda', 'Gabriel García Márquez', 'opcionB'),
('¿Qué novela fue escrita por Emily Brontë?', 'Jane Eyre', 'Cumbres borrascosas', 'Middlemarch', 'La inquilina de Wildfell Hall', 'opcionB'),
('¿Qué obra fue escrita por Goethe?', 'Werther', 'Crimen y castigo', 'La cartuja de Parma', 'El rojo y el negro', 'opcionA'),
('¿Quién escribió La tregua?', 'Eduardo Galeano', 'Mario Benedetti', 'Julio Cortázar', 'Gabriel García Márquez', 'opcionB'),
('¿Qué autor mexicano escribió Aura?', 'Octavio Paz', 'Carlos Fuentes', 'Juan Rulfo', 'José Emilio Pacheco', 'opcionB'),
('¿Qué novela fue escrita por Albert Camus?', 'La náusea', 'El extranjero', 'Ulises', 'El lobo estepario', 'opcionB'),
('¿Qué autor es conocido por su obra La insoportable levedad del ser?', 'Milan Kundera', 'Paul Auster', 'Haruki Murakami', 'Orhan Pamuk', 'opcionA'),
('¿Qué autor escribió Los juegos del hambre?', 'Veronica Roth', 'Suzanne Collins', 'J.K. Rowling', 'Cassandra Clare', 'opcionB'),
('¿Qué novela juvenil fue escrita por J.D. Salinger?', 'Las ventajas de ser invisible', 'El guardián entre el centeno', 'El dador de recuerdos', 'La lección de August', 'opcionB'),
('¿Qué poeta escribió Los heraldos negros?', 'César Vallejo', 'Vicente Huidobro', 'Rubén Darío', 'Pablo Neruda', 'opcionA'),
('¿Qué libro comienza con la frase “Llamadme Ismael”?', 'Moby-Dick', 'Robinson Crusoe', 'Drácula', 'El corazón de las tinieblas', 'opcionA'),
('¿Qué obra narra la historia de Gregorio Samsa, que se convierte en insecto?', 'El proceso', 'La metamorfosis', 'El castillo', 'El extranjero', 'opcionB'),
('¿Qué autor escribió La colmena?', 'Camilo José Cela', 'Miguel Delibes', 'Rafael Alberti', 'Antonio Machado', 'opcionA'),
('¿Qué novela inspiró la saga El Señor de los Anillos?', 'El Hobbit', 'Beowulf', 'La Ilíada', 'El Silmarillion', 'opcionA'),
('¿Qué autor escribió El amor en los tiempos del cólera?', 'Carlos Fuentes', 'Gabriel García Márquez', 'Jorge Luis Borges', 'Isabel Allende', 'opcionB'),
('¿Qué escritor creó el personaje de Tom Sawyer?', 'Mark Twain', 'Charles Dickens', 'Nathaniel Hawthorne', 'Louisa May Alcott', 'opcionA'),
('¿Qué autor escribió 1984 y Rebelión en la granja?', 'Ray Bradbury', 'Aldous Huxley', 'George Orwell', 'Philip K. Dick', 'opcionC'),
('¿Qué papa murió el 25 de abril de 2025?', 'Papa Nicolás V', 'Papa Francisco', 'Papa Pío II', 'Papa Benedicto XVI', 'opcionB'),
('¿En qué año se lanzó el videojuego "The Legend of Zelda: Ocarina of Time"?', '1997', '1998', '1999', '2000', 'opcionB'),
('¿De qué color es la piel de los osos polares?', 'blanca', 'negra', 'rosa', 'amarilla', 'opcionB'),
('¿Cuál es la célula responsable de la producción de insulina?', 'Neurona', 'Hematíe', 'Célula beta', 'Glóbulo blanco', 'opcionC'),
('¿Qué rey de Inglaterra fue conocido como "El Conquistador"?', 'Ricardo Corazón de León', 'Enrique VIII', 'Guillermo el Conquistador', 'Eduardo el Confesor', 'opcionC'),
('¿Qué personaje principal de "Halo" es conocido como "El Jefe Maestro"?', 'Cortana', 'Master Chief', 'The Arbiter', 'Dr. Halsey', 'opcionB'),
('¿Cuál es la principal función de los ribosomas en la célula?', 'Almacenar energía', 'Sintetizar proteínas', 'Descomponer nutrientes', 'Reproducir el ADN', 'opcionB'),
('¿Qué acontecimiento histórico marcó el fin de la Edad Media?', 'La caída del Imperio Romano', 'La Guerra de los Cien Años', 'La firma de la Carta Magna', 'La caída de Constantinopla', 'opcionD'),
('¿Qué videojuego es conocido por la frase "Hadouken"?', 'Street Fighter', 'Tekken', 'Mortal Kombat', 'Super Smash Bros.', 'opcionA'),
('¿Qué parte de la célula es responsable de la producción de energía?', 'Núcleo', 'Mitocondria', 'Lisósoma', 'Retículo endoplasmático', 'opcionB'),
('¿Quién escribió "La Odisea"?', 'Sófocles', 'Homero', 'Eurípides', 'Aristófanes', 'opcionB'),
('¿En qué país nació el videojuego "Super Mario Bros."?', 'Estados Unidos', 'Japón', 'Italia', 'Francia', 'opcionB'),
('¿Qué evento ocurrió en 1492 que tuvo gran impacto en la historia de América?', 'La independencia de México', 'La caída de Tenochtitlan', 'El descubrimiento europeo de América', 'La Revolución Francesa', 'opcionC'),
('¿Qué órgano del cuerpo humano es responsable de bombear la sangre?', 'Pulmón', 'Riñón', 'Hígado', 'Corazón', 'opcionD'),
('¿Cuál es la moneda oficial del Reino Unido?', 'Euro', 'Libra esterlina', 'Franco', 'Dólar', 'opcionB'),
('¿Qué descubrimiento hizo Charles Darwin que cambió la biología moderna?', 'La teoría del Big Bang', 'La teoría de la relatividad', 'La teoría de la evolución por selección natural', 'El descubrimiento de la penicilina', 'opcionC'),
('¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?', '1774', '1776', '1781', '1792', 'opcionB'),
('¿Qué videojuego se considera el primero de la saga "Pokémon"?', 'Pokémon Red/Blue', 'Pokémon Yellow', 'Pokémon Gold/Silver', 'Pokémon Ruby/Sapphire', 'opcionA'),
('¿Cuál es el nombre del gas que las plantas absorben para realizar la fotosíntesis?', 'Oxígeno', 'Dióxido de carbono', 'Nitrógeno', 'Hidrógeno', 'opcionB'),
('¿Quién fue el autor de la teoría heliocéntrica?', 'Galileo Galilei', 'Isaac Newton', 'Nicolás Copérnico', 'Johannes Kepler', 'opcionC'),
('¿Qué gas es más abundante en la atmósfera terrestre?', 'Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Hidrógeno', 'opcionB'),
('¿Qué instrumento mide la presión atmosférica?', 'Termómetro', 'Barómetro', 'Anemómetro', 'Altímetro', 'opcionB'),
('¿Qué país es conocido como la Tierra del Sol Naciente?', 'China', 'Japón', 'Corea del Sur', 'Tailandia', 'opcionB'),
('¿Quién pintó la Capilla Sixtina?', 'Leonardo da Vinci', 'Rafael', 'Miguel Ángel', 'Botticelli', 'opcionC'),
('¿Cuál es el número atómico del oxígeno?', '6', '8', '10', '12', 'opcionB');

INSERT INTO Casilla (idCasilla, idImagen, coordenadaX, coordenadaY, idPregunta) VALUES
(1, 1, 0, 0, 1),
(2, 1, 1, 0, 2),
(3, 1, 2, 0, 3),
(4, 1, 3, 0, 4),
(5, 1, 4, 0, 5),
(6, 1, 5, 0, 6),
(7, 1, 6, 0, 7),
(8, 1, 7, 0, 8),
(9, 1, 8, 0, 9),
(10, 1, 9, 0, 10),
(11, 1, 10, 0, 11),
(12, 1, 11, 0, 12),
(13, 1, 12, 0, 13),
(14, 1, 13, 0, 14),
(15, 1, 14, 0, 15),
(16, 1, 0, 1, 16),
(17, 1, 1, 1, 17),
(18, 1, 2, 1, 18),
(19, 1, 3, 1, 19),
(20, 1, 4, 1, 20),
(21, 1, 5, 1, 21),
(22, 1, 6, 1, 22),
(23, 1, 7, 1, 23),
(24, 1, 8, 1, 24),
(25, 1, 9, 1, 25),
(26, 1, 10, 1, 26),
(27, 1, 11, 1, 27),
(28, 1, 12, 1, 28),
(29, 1, 13, 1, 29),
(30, 1, 14, 1, 30),
(31, 1, 0, 2, 31),
(32, 1, 1, 2, 32),
(33, 1, 2, 2, 33),
(34, 1, 3, 2, 34),
(35, 1, 4, 2, 35),
(36, 1, 5, 2, 36),
(37, 1, 6, 2, 37),
(38, 1, 7, 2, 38),
(39, 1, 8, 2, 39),
(40, 1, 9, 2, 40),
(41, 1, 10, 2, 41),
(42, 1, 11, 2, 42),
(43, 1, 12, 2, 43),
(44, 1, 13, 2, 44),
(45, 1, 14, 2, 45),
(46, 1, 0, 3, 46),
(47, 1, 1, 3, 47),
(48, 1, 2, 3, 48),
(49, 1, 3, 3, 49),
(50, 1, 4, 3, 50),
(51, 1, 5, 3, 51),
(52, 1, 6, 3, 52),
(53, 1, 7, 3, 53),
(54, 1, 8, 3, 54),
(55, 1, 9, 3, 55),
(56, 1, 10, 3, 56),
(57, 1, 11, 3, 57),
(58, 1, 12, 3, 58),
(59, 1, 13, 3, 59),
(60, 1, 14, 3, 60),
(61, 1, 0, 4, 61),
(62, 1, 1, 4, 62),
(63, 1, 2, 4, 63),
(64, 1, 3, 4, 64),
(65, 1, 4, 4, 65),
(66, 1, 5, 4, 66),
(67, 1, 6, 4, 67),
(68, 1, 7, 4, 68),
(69, 1, 8, 4, 69),
(70, 1, 9, 4, 70),
(71, 1, 10, 4, 71),
(72, 1, 11, 4, 72),
(73, 1, 12, 4, 73),
(74, 1, 13, 4, 74),
(75, 1, 14, 4, 75),
(76, 1, 0, 5, 76),
(77, 1, 1, 5, 77),
(78, 1, 2, 5, 78),
(79, 1, 3, 5, 79),
(80, 1, 4, 5, 80),
(81, 1, 5, 5, 81),
(82, 1, 6, 5, 82),
(83, 1, 7, 5, 83),
(84, 1, 8, 5, 84),
(85, 1, 9, 5, 85),
(86, 1, 10, 5, 86),
(87, 1, 11, 5, 87),
(88, 1, 12, 5, 88),
(89, 1, 13, 5, 89),
(90, 1, 14, 5, 90),
(91, 1, 0, 6, 91),
(92, 1, 1, 6, 92),
(93, 1, 2, 6, 93),
(94, 1, 3, 6, 94),
(95, 1, 4, 6, 95),
(96, 1, 5, 6, 96),
(97, 1, 6, 6, 97),
(98, 1, 7, 6, 98),
(99, 1, 8, 6, 99),
(100, 1, 9, 6, 100),
(101, 1, 10, 6, 101),
(102, 1, 11, 6, 102),
(103, 1, 12, 6, 103),
(104, 1, 13, 6, 104),
(105, 1, 14, 6, 105),
(106, 1, 0, 7, 106),
(107, 1, 1, 7, 107),
(108, 1, 2, 7, 108),
(109, 1, 3, 7, 109),
(110, 1, 4, 7, 110),
(111, 1, 5, 7, 111),
(112, 1, 6, 7, 112),
(113, 1, 7, 7, 113),
(114, 1, 8, 7, 114),
(115, 1, 9, 7, 115),
(116, 1, 10, 7, 116),
(117, 1, 11, 7, 117),
(118, 1, 12, 7, 118),
(119, 1, 13, 7, 119),
(120, 1, 14, 7, 120),
(121, 1, 0, 8, 121),
(122, 1, 1, 8, 122),
(123, 1, 2, 8, 123),
(124, 1, 3, 8, 124),
(125, 1, 4, 8, 125),
(126, 1, 5, 8, 126),
(127, 1, 6, 8, 127),
(128, 1, 7, 8, 128),
(129, 1, 8, 8, 129),
(130, 1, 9, 8, 130),
(131, 1, 10, 8, 131),
(132, 1, 11, 8, 132),
(133, 1, 12, 8, 133),
(134, 1, 13, 8, 134),
(135, 1, 14, 8, 135),
(136, 1, 0, 9, 136),
(137, 1, 1, 9, 137),
(138, 1, 2, 9, 138),
(139, 1, 3, 9, 139),
(140, 1, 4, 9, 140),
(141, 1, 5, 9, 141),
(142, 1, 6, 9, 142),
(143, 1, 7, 9, 143),
(144, 1, 8, 9, 144),
(145, 1, 9, 9, 145),
(146, 1, 10, 9, 146),
(147, 1, 11, 9, 147),
(148, 1, 12, 9, 148),
(149, 1, 13, 9, 149),
(150, 1, 14, 9, 150),
(151, 1, 0, 10, 151),
(152, 1, 1, 10, 152),
(153, 1, 2, 10, 153),
(154, 1, 3, 10, 154),
(155, 1, 4, 10, 155),
(156, 1, 5, 10, 156),
(157, 1, 6, 10, 157),
(158, 1, 7, 10, 158),
(159, 1, 8, 10, 159),
(160, 1, 9, 10, 160),
(161, 1, 10, 10, 161),
(162, 1, 11, 10, 162),
(163, 1, 12, 10, 163),
(164, 1, 13, 10, 164),
(165, 1, 14, 10, 165),
(166, 1, 0, 11, 166),
(167, 1, 1, 11, 167),
(168, 1, 2, 11, 168),
(169, 1, 3, 11, 169),
(170, 1, 4, 11, 170),
(171, 1, 5, 11, 171),
(172, 1, 6, 11, 172),
(173, 1, 7, 11, 173),
(174, 1, 8, 11, 174),
(175, 1, 9, 11, 175),
(176, 1, 10, 11, 176),
(177, 1, 11, 11, 177),
(178, 1, 12, 11, 178),
(179, 1, 13, 11, 179),
(180, 1, 14, 11, 180),
(181, 1, 0, 12, 181),
(182, 1, 1, 12, 182),
(183, 1, 2, 12, 183),
(184, 1, 3, 12, 184),
(185, 1, 4, 12, 185),
(186, 1, 5, 12, 186),
(187, 1, 6, 12, 187),
(188, 1, 7, 12, 188),
(189, 1, 8, 12, 189),
(190, 1, 9, 12, 190),
(191, 1, 10, 12, 191),
(192, 1, 11, 12, 192),
(193, 1, 12, 12, 193),
(194, 1, 13, 12, 194),
(195, 1, 14, 12, 195),
(196, 1, 0, 13, 196),
(197, 1, 1, 13, 197),
(198, 1, 2, 13, 198),
(199, 1, 3, 13, 199),
(200, 1, 4, 13, 200),
(201, 1, 5, 13, 201),
(202, 1, 6, 13, 202),
(203, 1, 7, 13, 203),
(204, 1, 8, 13, 204),
(205, 1, 9, 13, 205),
(206, 1, 10, 13, 206),
(207, 1, 11, 13, 207),
(208, 1, 12, 13, 208),
(209, 1, 13, 13, 209),
(210, 1, 14, 13, 210),
(211, 1, 0, 14, 211),
(212, 1, 1, 14, 212),
(213, 1, 2, 14, 213),
(214, 1, 3, 14, 214),
(215, 1, 4, 14, 215),
(216, 1, 5, 14, 216),
(217, 1, 6, 14, 217),
(218, 1, 7, 14, 218),
(219, 1, 8, 14, 219),
(220, 1, 9, 14, 220),
(221, 1, 10, 14, 221),
(222, 1, 11, 14, 222),
(223, 1, 12, 14, 223),
(224, 1, 13, 14, 224),
(225, 1, 14, 14, 225);

/*INSERT INTO Casilla (idCasilla, idImagen, coordenadaX, coordenadaY, idPregunta) VALUES
(1, 1, 0, 0, 1),
(2, 1, 1, 1, 2),
(3, 1, 2, 2, 3);
INSERT INTO IntentoCorrecto (idUsuario, idCasilla, idImagen) VALUES
(1, 1, 1);
INSERT INTO IntentoIncorrecto (opcionElegida, idUsuario, idCasilla, idImagen) VALUES
('opcionB', 1, 1, 1);*/

